-- =============================================================================
-- Script   : 05_magnitude_analysis.sql
-- Author   : Uzair Akhtar
-- GitHub   : https://github.com/HafizUzairAkhtar
-- =============================================================================
-- Purpose:
--     This script breaks down key metrics by different dimensions to understand
--     the distribution and size of data across categories, countries, genders,
--     and customers.
--
--     Magnitude analysis answers questions like:
--     "Which country has the most customers?"
--     "Which product category generates the most revenue?"
--     "Which customers spend the most?"
--
-- SQL Functions Used:
--     SUM()      → Totals up numeric values within each group
--     COUNT()    → Counts records within each group
--     AVG()      → Calculates average values within each group
--     GROUP BY   → Groups rows by a dimension for aggregation
--     ORDER BY   → Sorts results so highest values appear first
--     LEFT JOIN  → Combines fact and dimension tables, keeping all fact rows
--
-- Tables Used:
--     gold.fact_sales     → Sales transactions (facts)
--     gold.dim_customers  → Customer details (dimension)
--     gold.dim_products   → Product details (dimension)
--
-- Execution Order:
--     Run this script after: 04_measures_exploration.sql
--     Next step: 06_ranking_analysis.sql
-- =============================================================================


-- Step 1: Find total number of customers by country
--         This shows us where our customer base is concentrated geographically.
--         Sorted descending so the largest markets appear at the top.
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Step 2: Find total number of customers by gender
--         Useful for understanding the gender split of our customer base
--         before doing any demographic segmentation.
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Step 3: Find total number of products by category
--         Tells us how the product catalog is distributed across categories.
--         A category with very few products may be underrepresented.
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Step 4: Find the average product cost by category
--         This reveals which categories carry higher-cost products.
--         Useful for comparing pricing strategy across the product range.
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- Step 5: Find total revenue generated by each product category
--         We join fact_sales with dim_products to bring in the category.
--         This is one of the most important business questions — which
--         category drives the most money for the business.
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Step 6: Find total revenue generated by each customer
--         We join fact_sales with dim_customers to get customer names.
--         This gives us a per-customer revenue view, which feeds directly
--         into ranking and segmentation analysis in later scripts.
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- Step 7: Find total items sold by country
--         This shows where the highest sales volume (quantity) comes from.
--         Note: quantity is different from revenue — a country can sell
--         many low-cost items and still rank lower in revenue.
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


-- Step 8: Find total revenue generated by each country
--         Combines country dimension with sales fact to see revenue by region.
--         Compare this with Step 7 to spot any country where volume is high
--         but revenue is low — a sign of low-value purchases.
SELECT
    c.country,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_revenue DESC;


-- =============================================================================
-- Analysis complete.
-- You now understand how key metrics are distributed across all major dimensions.
-- Next step: Run 06_ranking_analysis.sql
-- =============================================================================